### PR TITLE
Updated home page with content defined in Miro

### PR DESCRIPTION
**Pull request by Enotmd**
Modified pages/index.js  so that homepage matches Miro design as per requested in : https://github.com/web-seven/website/issues/40

### CODE REVIEW

**Review by web7evgheni — CHANGES_REQUESTED** [review]
@Enotmd Please check and update:
screenshot-localhost_3000-2023 12 11-11_34_12

**Comment by Enotmd** [comment]
@web7evgheni 
image (before changes in component)
Teaser List component will display bullet list if we modify src/components/TeasersList.tsx like i did.  Please consider this too. 
(after changes) 
image
Will add Lucian to review if it's ok to be edit like this.

**Comment by web7evgheni** [comment]
> @web7evgheni image (before changes in component) Teaser List component will display bullet list if we modify src/components/TeasersList.tsx like i did. Please consider this too. (after changes) image Will add Lucian to review if it's ok to be edit like this.

@Enotmd Please do not use there list, is from information structure bad to have it there. Shall simple text under teaser title.

**Review by web7evgheni — CHANGES_REQUESTED** [review]
@Enotmd Please use sentences for non technical users on teasers, as discussed

**Review by web7evgheni — APPROVED** [review]

**Pull request merged**
